import React from 'react';
import { useReports } from '../hooks/useReports';
import ReportsHeader from '../components/reports/ReportsHeader';
import ReportTabs from '../components/reports/ReportTabs';
import SalesAnalytics from '../components/reports/SalesAnalytics';
import ProductionAnalytics from '../components/reports/ProductionAnalytics';
import StockAlerts from '../components/reports/StockAlerts';

export default function Reports() {
  const {
    activeTab,
    dateRange,
    reportData,
    loading,
    actions
  } = useReports();

  return (
    <div className="h-full flex flex-col bg-[var(--color-bg-app)] text-zinc-100 p-6 overflow-hidden font-sans">
      <ReportsHeader
        dateRange={dateRange}
        setDateRange={actions.setDateRange}
        handlePrint={actions.handlePrint}
      />

      <ReportTabs
        activeTab={activeTab}
        setActiveTab={actions.setActiveTab}
      />

      <div className="flex-1 overflow-y-auto custom-scrollbar pr-2 space-y-6">
        {loading ? (
          <div className="text-zinc-500 text-center py-20">Loading report data...</div>
        ) : (
          <>
            {activeTab === 'sales' && <SalesAnalytics data={reportData} />}
            {activeTab === 'production' && <ProductionAnalytics data={reportData} />}
            {activeTab === 'stock' && <StockAlerts data={reportData} />}
          </>
        )}
      </div>

      {/* Print Footer (Only visible when printing) */}
      <div className="hidden print:block fixed bottom-0 left-0 w-full text-center text-xs text-black p-4 bg-white">
        Generated by VELORA POS System on {new Date().toLocaleString()}
      </div>
    </div>
  );
}
